### ISSUE TITLE
False documentation entry

### ISSUE THREAD

**Issue by BuckUbel** [Lusito/react-router-ts#1]
In your readme you have suggested a default routeMatcher which uses path-to-regexp. 
You also noted that with "\*" as path parameter the default route can be defined. 
Because of an update this has changed and now "(.*)" must be set as prop.
Can you please update the readme ?

**Comment by Lusito** [comment]
Thanks for the report, but the "*" is actually for the [simpleRouteMatcherFactory](https://github.com/Lusito/react-router-ts/blob/master/src/simpleRouteMatcherFactory.ts), which is included by default.

I guess the description is a bit confusing, so I'll see how to write this more clearly.

**Comment by Lusito** [comment]
I've updated the readme. Please check if the new text is clearly describing the issue at hand.

**Comment by BuckUbel** [comment]
Many thanks for your quick response!
I think it is now more clearly formulated.
