### ISSUE TITLE
Is it possible to pass `location` as prop to the component being routed to?

### ISSUE THREAD

**Issue by websocket98765** [Lusito/react-router-ts#2]
I'm trying to switch from react-router, where components automatically had access to `this.props.location` supplied by the router.

Is it possible to pass this somehow when using `react-router-ts`? 

I tried:
```js
  <Router location={window.location}>
    <Route path="/" component={App} />
  </Router>
```
and 
```js
  <Router>
    <Route path="/" component={App} location={window.location} />
  </Router>
```
with no luck.

Ideally it would be passed automatically.

**Comment by Lusito** [comment]
You don't have access to window location itself via react-router-ts. But if you actually needed that, you could just use window.location.

So I'm guessing you want access to the path portion from within a component? In that case, you can use the useRouter hook:

```typescript
const path = useRouter().path;
```

If that is not what you are looking for, could you specify what exactly you are trying to do?

**Comment by websocket98765** [comment]
I have a search-based app using Algolia. The path is always `/`, but query string changes as the as search query and refinements change.

The app then uses the location prop to know if it needs to refresh:
`const App = ({ location, history }) => {`
(This full App.jsx example is at <https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/react/>, which is based on react-router, which passes location and history params.) 

Unless it would harm performance, maybe you could pass location to the component being routed to? Or even both location & history? Or maybe I just can't use it, but saving 22kb over react-router would be awesome.

**Comment by Lusito** [comment]
alright, so I tried reproducing this with the sample in your provided URL:
https://codesandbox.io/s/prod-sky-cnnmg?file=/src/App.js

This works, but there is a bug in react-router-ts, which requires the path="*" in the index.js:
When pushing a new path which includes a search query (or hash), the search and hash are included in the path property, causing the path matching to fail.

I will create a fix for this. Other than that, it seems that you don't need anything else from react-router-ts. You can just use document.location instead of props.location.

**Comment by Lusito** [comment]
Fix has been released and the codesandbox adjusted accordingly

**Comment by websocket98765** [comment]
Above and beyond. (Looks like something changed recently--`react-router-ts` causing `basename is undefined` due to an issue in `react-router-ts/dist/basename.js`.)

The remaining question though for `react-rotuer-ts`'s approach, is if a _browser back/forward button_ will be able to inform the App that it has updated witihout using props. With React Router, this can be solved using `useEffect` because a change to the location prop causes useEffect to run. Not sure conceptually how it's possible to solve that without notifying the App via a prop.

**Comment by Lusito** [comment]
I'm honestly not sure what is causing the error, but it only seems to happen on code-sandbox. If I try this locally, the error does not happen.

When I created the sandbox above, it still worked, so my best guess is, that codesandbox introduced a bug. Can you reproduce the issue locally?

About the browser back/forward button: If you use the useRouter hook, then the component using it will be updated when the back/forward buttons are used. You can use useEffect as well, as seen in the sandbox above. Granted, you might want to add document.location.search to the dependencies of the useEffect.

**Comment by websocket98765** [comment]
Got it working beautifully locally!

`window.location.search` within `useEffect()`'s dependency array is required, as you mentioned, in order to back/forward history buttons to work when only the query string is updated in the URL between pages.

```javascript
useEffect(() => {
  // ...
}, [router.path, window.location.search]);
```

ESLint complains about it being there (below), but it's definitely required for back/forward browser history buttons to work, so ESLint seems to just be wrong in this case:
```
React Hook useEffect has an unnecessary dependency: 'window.location.search'. 
Either exclude it or remove the dependency array. Outer scope values like 
'window.location.search' aren't valid dependencies because mutating them 
doesn't re-render the component.eslint(react-hooks/exhaustive-deps)
```

This is awesome! Happy to have it working. Thanks for the help!!

**Comment by Lusito** [comment]
The reason why it's complaining about `window.location.search` is, that you don't use it within the effect itself. You can avoid this by passing `window.location.search` to `urlToSearchState` instead of using it directly.
