### ISSUE TITLE
Unexpected token 'export'

### ISSUE THREAD

**Issue by websocket98765** [Lusito/react-router-ts#3]
I encountered the same error that we saw on the sandbox again. This time when running a Jest test that shallow renders my main `<App />` component using Enzyme:

It seems to be triggered by using `import { useRouter } from 'react-router-ts';`, since this line is pointed out in the error message. That's also about when we saw the error on the sandbox too, after it was updated to use that.

```
/node_modules/react-router-ts/dist/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest)
    {export * from "./basename";                 
     ^^^^^^
    SyntaxError: Unexpected token 'export'

    > 
    > 19 | import { useRouter } from 'react-router-ts';
    > 
    
    at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
    at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
    at Object.<anonymous> (src/components/App.jsx:19:1)
```

Possibly an issue with the build script not compiling the `./basename` file?

Interestingly, my app runs fine. Only my tests causes the error.

**Comment by Lusito** [comment]
This library is shipped as es2015 modules. jest doesn't support this natively yet, see these topics for various workarounds:
https://github.com/nrwl/nx/issues/812#issuecomment-429420861
https://github.com/facebook/jest/issues/4842
https://github.com/facebook/jest/issues/2081

I've used the first one successfully. I.e. change your jest.config.js to this:

```javascript
const esModules = ['react-router-ts'].join('|');
// ...
module.exports = {
  //...
    transformIgnorePatterns: [`/node_modules/(?!${esModules})`],
  // ...
};
```

I thought about providing an additional commonjs build to avoid these kind of issues in outdated tools, but I didn't get to do the research yet.
